### ISSUE TITLE
Link's Hands Revert to "No-gloves" state when being shocked

### ISSUE THREAD

**Issue by Nicholas-Steel** [Dessyreqt/alttprandomizer#294]
https://www.youtube.com/watch?v=HA08xfRMR_0&index=2&list=PLnECGpr5DfBv-Zk-YsthAaJIQ_hNAGhSU

This is v6 of the Randomizer, I do not know if this was fixed in v7. If you watch from the start you'll notice him commenting on it within the first 5 minutes of the video and then the game fixes the colour of the characters gloves when he picks up a rock.

**Comment by BlueViper85** [comment]
I watched this video when it was released, and remember his comment. Watching this video and the others after, it was hard to tell since he barely stops moving. I've not noticed this issue first hand playing any version of the randomizer, though I've admittedly gone back and forth on whether or not it did but never gave it much weight, since the Titan's Mitts have always looked better..  Trying to re-watch this video I still couldn't find any solid evidence that this was really an issue.

So in the interest of being thorough, I tested this in three versions:

-Vanilla ALttP Japanese 1.0 (the base game for the Randomizer)
-Randomizer V6
-Randomizer V7

In each case, I went to the area in front of Link's door and looked at link's hands and observed the color.  This ensured consistent coloring in each actual view and screenshot to ensure neighboring colors were throwing things off.

I tested three scenarios with each version of the ROM:

1. Without the power gloves
2. With the power gloves, but without saving and quitting after getting them
3. With the power gloves, after saving and quitting (to follow your original title)

In each instance, the hands were the same color as Link's skin (more or less anyway, could also be brown gloves?) when I didn't have the Power Gloves, and after getting the power gloves they were Grey in all instances (regardless of saving and quitting).

Here is an album of screenshots (one for each scenario) as supporting documentation. http://imgur.com/a/4PFh1

**Comment by churine** [comment]
The gloves being the wrong color is actually a known glitch from vanilla aLttP. (I recall seeing a bugfix patch for it somewhere?)

There are a few specific things that incorrectly undo the Power Glove and Titan's Mitt palettes to the hands: I don't recall all of them but at the top of my head viewing the map and maybe getting shoked (by the barrier?) colors Link's hands as his skin, while changing scenes (entrance/exit, S&Q etc) reset them to the correct one.

This is not fixed in the randomizer.

**Comment by churine** [comment]
@BlueViper85 I don't know how to properly request this to be re-opened so hopefully this works.

I was also mistaken: while in a dungeon the glitch may be delayed to occur after going through stairs instead of immediately after viewing the map, and seems to remain for the entire dungeon.
Getting shocked by anything, and transforming into a bunny also cause the glitch.

S&Q, Entrance/Exit, flying with the bird, warping between worlds or using the mirror reset it correctly.

**Comment by BlueViper85** [comment]
@zilarch The issue, as it was originally stated in the opening comment was shown to not be the case, hence the "invalid" tag.  You couldn't reopen the issue because you weren't the original submitter, but e-mail notifications still get sent to those who are setup to receive them.

After doing significant more testing with your statements two things changed Link's hand color:

1. Getting shocked
2. Becoming a bunny and mirroring back to Light World

Both of which are fixed by entering/exiting a dungeon/cave door.  

Using the map, changing floor layers, and various other combinations did not change the hand color.  Going back through a door 

Before shock
<img width="93" alt="11 - link with gloves outside aga tower before shock" src="https://cloud.githubusercontent.com/assets/12190332/21951720/00f410bc-d9d1-11e6-9261-32ed8e277c86.PNG">

After shock
<img width="81" alt="12 - link with gloves outside aga tower after shock" src="https://cloud.githubusercontent.com/assets/12190332/21951719/00f2fa38-d9d1-11e6-85f3-aa308a409999.PNG">

I've corrected the title and updated the tag accordingly and I will reopen this for now.  Given that you can look at the start menu to validate that gloves that you have, and that the impact is minimal since it's not gameplay-affecting, this will likely be low on the priority list and may be closed again without being fixed depending on the ease of the fix compared to the benefit.

**Comment by churine** [comment]
That's very strange, I can reproduce it without fail:
![map glitch](http://i.imgur.com/vQioCMC.gif) this is on v7
(the video does show the glitch, it's only the rock part what was incorrect: he starts with the glitch in effect, and it gets fixed seconds later when he enters in a cave. He only notices when picking up a rock)

I know it's a tiny bug (I didn't even feel it was worth reporting since I assumed everyone was aware of it and is from the vanilla game... not to mention affects eight pixels), but I'm intrigued since no matter how I can't make the map not cause it.

![easier to see one with Power Gloves](http://i.imgur.com/tg7MnXc.gif)

As for dungeons, I should've clarified I meant door stairs. Layer stairs do not affect this at all.

**Comment by BlueViper85** [comment]
I've never paid any atttention to Link's hands throughout any play through. I've always tracked my gloves through the item menu or just remembering what I have. But I digress...

I tried both floor changing stairs and layer changing stairs and it didn't happen on either same as the map.

In any event, since you actually provided a video shows it happening, I think we have sufficient evidence and I'm leaving it up to the people who can actually fix this to determine if it's worth fixing or not or someone else involved in the project to chime in.

Being a vanilla issue that's incredibly minor I don't care if it's fixed either way (leaning a little more towards a "don't fix it" opinion, honestly) and our goal in general isn't focused much on vanilla glitches except where it has a significant impact when playing the game.

**Comment by ChristosOwen** [comment]
eurgh

**Comment by ChristosOwen** [comment]
Vanilla behaviour, not going to fix.
